name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # - name: Install serve
      #   run: yarn global add serve

      # - name: Install dependencies
      #   run: yarn install

      # - name: Build app
      #   run: yarn build

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_baseUrl: https://example-my-app.vercel.app
