name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Wait for Vercel
        uses: UnlyEd/github-action-await-vercel@v1.2.14
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: example-my-app.vercel.app # TODO Replace by the domain you want to test
          timeout: 10 # Wait for 10 seconds before failing

      - name: Display deployment status
        run: "echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}"

      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # - name: Install serve
      #   run: yarn global add serve

      # - name: Install dependencies
      #   run: yarn install

      # - name: Build app
      #   run: yarn build

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: fromJson(steps.await-vercel.outputs.deploymentDetails).url
